env:
  # Device env
  DEVICE_NAME : "Motorola S30 Pro"
  DEVICE_CODENAME : "tundra"
  
  # 编译参数
  CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu-"
  EXTRA_CMDS : "LD=ld.lld LLVM=1 LLVM_IAS=1"
  
  # --- 1. 内核源码 (已切换为 Moto 官方开源) ---
  KERNEL_SOURCE : "https://github.com/MotorolaMobilityLLC/kernel-msm.git"
  KERNEL_BRANCH : "MMI-U1SJS34.2-92-10-3"

  # --- 2. 编译器 (强烈建议升级，原版太旧无法编译 A14 内核) ---
  # 使用 Android 14 对应的 Clang r487747c
  CLANG_SOURCE : "https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-14.0.0_r0.75/clang-r487747c.tar.gz"
  CLANG_BRANCH : "main"
  
  GCC_GNU : true
  GCC_64_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git"
  GCC_64_BRANCH : "android-12.1.0_r27"
  GCC_32_SOURCE : "https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9.git"
  GCC_32_BRANCH : "android-12.1.0_r27"

  # --- 3. Defconfig 配置 (修复报错的关键) ---
  DEFCONFIG_SOURCE: ""
  # 这里必须填写，脚本会将提取出的配置保存为这个文件名
  DEFCONFIG_NAME : "tundra_defconfig" 
  # 官方 boot.img 下载地址
  DEFCONFIG_ORIGIN_IMAGE: "https://github.com/Meltemi-9264/NonGKI_Kernel_Build_2nd/releases/download/v1.0-boot/boot.img"
  DEFCONFIG_FROM_BOOT: true

  # --- KernelSU & SusFS 设置 ---
  KERNELSU_SOURCE : "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh"
  KERNELSU_BRANCH : "susfs-dev"
  KERNELSU_AUTO_GET : "true"
  KERNELSU_AUTO_FORK : "sukisu"
  SUSFS_ENABLE : false
  SUSFS_FIXED : false
  SUSFS_UPDATE : false

  # --- 打包工具 ---
  AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
  AK3_BRANCH : "master"
  BOOT_SOURCE : ""
  
  # --- 其他设置 ---
  NEED_DTBO : false
  NEED_SAFE_DTBO : false
  ROM_TEXT : "myui_a14"
  PYTHON_VERSION: "3"
  PACK_METHOD: "Anykernel3"
  KERNELSU_METHOD: "shell"
  PATCHES_SOURCE: "false"
  PATCHES_BRANCH: "false"
  SUSFS_FOLDER_FIXED: ""
  SUSFS_155_FIXED: ""
  SUSFS_151X_FIXED: ""
  SUSFS_LATEST_FIXED: ""
  REKERNEL_ENABLE: "false"
  HYMOFS_ENABLE: "false"
  HOOK_METHOD: "syscall"
  HOOK_OLDER: "false"
  KPM_ENABLE: "false"
  KPM_PATCH_SOURCE: ""
  BASEBAND_GUARD_ENABLE: "false"
  BASEBAND_GUARD_BOOT: "false"
  HIDE_STUFF: "false"
  GENERATE_DTB: "false"
  GENERATE_CHIP: "qcom"
  BUILD_DEBUGGER: "false"
  SKIP_PATCH: "false"
  BUILD_OTHER_CONFIG: ""
  MERGE_CONFIG_FILES: ""
  FREE_MORE_SPACE: "true"
